### ISSUE TITLE
Add Marketplace AMIs

### ISSUE THREAD

**Issue by benofben** [aws-quickstart/quickstart-neo4j#11]
Right now we're using platform images.  Need to create dummy marketplace images first.

**Comment by benofben** [comment]
Dummy images now exist.  We would need to reference them here.  If we did that, Quick Start use would show in Marketplace reporting.  The downside is that the clever platform image reference code would need to be replaced with an AMI map.

**Comment by harshitsinghvi22** [comment]
this is implemented
